DAY 8

function user(name,age,work,hobbies){
  return{
    name:name,
    age:age,
    work:work,
    hobbies:hobbies,
  }
}
const vsr=user("vishal",19,"student","cricket");
console.log(vsr);
const mom=user("nitudevi",41,"house wife","comedy");
console.log(mom);
const papa=user("pawan singh",43,"manager","chess");
console.log(papa);
const didi=user("priya","20","teacher","running");
console.log(didi);
